### ISSUE TITLE
Still working with laravel 5.7?

### ISSUE THREAD

**Issue by kamov** [igaster/laravel-model-options#1]
I would like to know if this is still working on laravel 5.7?

i see there is not update in last 3 years

**Comment by kamov** [comment]
And does this work if column is just a "text" field and not json field?

**Comment by igaster** [comment]
Hello @kamov, yes this works fine with latest Laravel versions... It is a simple package so it is not affected by Laravel versions... Probably I can update the test suite to test against Laravel 5.7 too...

About the json mysql type, I don't think that there would be any advantages compared with plain text type, as long as we don't use mysql built-in json methods... Probably text is faster because mysql doesn't have to process data on insert... I don't know if someone has better insights about this topic...

**Comment by kamov** [comment]
Thanks for your reply. That make sense to me. I will test your package.

**Comment by igaster** [comment]
Hello @kamov, I updated tests with Laravel 5.7. 
Also a small issue was fixed.

Thanks for bringing my attention here!
You may pull latest release.
